config/routes.rb
Rails.application.routes.draw do
  resources :repositories do
    get "export", on: :collection
  end
  get "/", to: redirect("/repositories")
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  class QueryError < StandardError; end

  private
    def query(definition, variables = {})
      response = GitHub::Client.query(definition, variables: variables, context: client_context)

      if response.errors.any?
        raise QueryError.new(response.errors[:data].join(", "))
      else
        response.data
      end
    end

    # Public: Useful helper method for tracking GraphQL context data to pass
    # along to the network adapter.
    def client_context
      # Use static access token from environment. However, here we have access
      # to the current request so we could configure the token to be retrieved
      # from a session cookie.
      { access_token: GitHub::Application.secrets.github_access_token }
    end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  require 'csv' 

  IndexQuery = GitHub::Client.parse <<-'GRAPHQL'
    query($after: String){
    search(query: "org:google", type: REPOSITORY, first: 100, after: $after) {
      repositoryCount
      pageInfo {
        endCursor
        startCursor
        hasNextPage
      }
      edges {
        node {
          ... on Repository {
            name
            createdAt
            primaryLanguage {
              name
            }
            
            
          }
        }
      }
    }
  }
  GRAPHQL
  
  # GET list of all repositories
  def index
    fetch_repositories #fetch all repositories of google organisation
    find_top_least(@repo) #find out top 5 and least 5 languages used by google organisation
  end

  # GET export to CSV file
  def export
    fetch_repositories #fetch all repositories of google organisation
    file = "#{Rails.root}/public/repositories.csv"
    headers = ["Name", "language", "CreatedAt"]
    CSV.open(file, 'w', write_headers: true, headers: headers) do |writer|
      @repo.each do |repo| 
      writer << [repo[:name],repo[:language], repo[:created_at]] 
      end
    end

    send_file(file, type: "text/csv", filename: "repositories.csv", disposition: "attachment")
  end

  def fetch_repositories
    @repo, has_next, after = [], true, nil
    while has_next
      data = query IndexQuery, after: after
      has_next = data.search.page_info.has_next_page?
      after = data.search.page_info.end_cursor
      JSON.parse(data.to_json).first.second["search"]["edges"].each do |node |
        language = node["node"]["primaryLanguage"]["name"] rescue ""
        @repo << { name: node["node"]["name"], language: language, created_at: node["node"]["createdAt"] }
      end
      puts @repo.count
    end
  end

  def find_top_least(repo)
    languages = repo.map{|x| x[:language]}.reject { |c| c.empty? }
    occurances =  languages.inject(Hash.new(0)) { |h,v| h[v] += 1; h }.sort_by{ |k, v| [v, k]}.reverse
    @top_languages = occurances.first(5)
    @least_languages = occurances.last(5)
    puts "top languages->>> #{@top_languages}"
    puts "least languages->>> #{@least_languages}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GraphQL Demo</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="/application.css">
    <script src="/application.js"></script>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/repositories/index.html.erb
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css
">
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/dataTables.jqueryui.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/scroller/2.0.3/css/scroller.jqueryui.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/dataTables.jqueryui.min.js
"></script>
<script src="https://cdn.datatables.net/scroller/2.0.3/js/dataTables.scroller.min.js"></script>

<style type="text/css">
  .flex-container{
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    padding: 20px;
    width: 100%;
  }
  .item{
    margin: 0;
    display: inherit;
    padding: 10px;
    width: 100%;
    height: 100px;
    align-items: center;
    flex-wrap: wrap;
    font-size: 20px;
  }
  .right{
    float: right;
  }

</style>
<h3> Top 5 Used Languages by Organisation</h3>
<div class="flex-container">
  <% @top_languages.each do |lang| %> 
  <div class="item"><li> <%= lang[0] %></li></div>
  <% end %>
</div>

<h3> Least 5 Used Languages by Organisation </h3>
<div class="flex-container">
  <% @least_languages.each do |lang| %> 
  <div class="item"><li> <%= lang[0] %></li></div>
  <% end %>
</div>

<%= link_to "export", export_repositories_path(format: "csv"), class: "btn btn-primary right" %><br><br>

<table id="repo_table" class="display nowrap" style="width:100%">
  <thead>
    <tr>
      <th>Repo name</th>
      <th>Language</th>
      <th>Created at</th>
    </tr>
  </thead>
  <tbody>
    <% @repo.each do |repo| %> 
    <tr>
      <td><%= repo[:name] %> </td>
      <td><%= repo[:language] %> </td>
      <td><%= repo[:created_at] %> </td>
    </tr>
    <% end %>
  </tbody>
</table>

<script type="text/javascript">
  $(document).ready(function(){
    $('#repo_table').DataTable();
  });
</script>